"""
gen_deep_qnn.py — generate deep (ZZ-feature-map) QNN circuits at 100 and 200
qubits, matching the v1.1.0 construction used at 25 and 64 qubits.

Background.  MQT Bench v1.1.0 built its `qnn` benchmark from a ZZFeatureMap,
whose data encoding entangles every pair of qubits; v2.2.2 switched to a
ZFeatureMap, which is a product state and leaves the circuit a linear chain of
n-1 CX gates.  The suite's own qnn_25 (1223 CX) and qnn_64 (8126 CX) are the
v1.1.0 form; qnn_100 and qnn_200 in the circuits directory are the v2.2.2 form
and carry 99 and 199 CX respectively, which is too shallow to discriminate
between routers.

The v1.1.0 construction was recovered by matching CX counts exactly:

    ZZFeatureMap(n, reps=2) o RealAmplitudes(n, reps=1)
    transpile(basis=[rz,sx,x,cx], optimization_level=3, seed_transpiler=0)

reproduces 1223 CX at n=25 and 8126 at n=64, matching the suite files.

These circuits are quadratic in n (~2n^2 CX): 19,899 at 100 qubits and 79,799
at 200.  For comparison the largest circuit in any current suite is
multiplier_64 at 13,040 CX.  Budget routing time accordingly, and do not expect
pytket-dqc's embedding distributors to complete on them - they already fall
back on the 8126-CX qnn_64.

These were adopted as the canonical qnn_100 / qnn_200 on 2026-07-27; the
previous shallow files are kept beside them as
qnn_SHALLOW_v2.2.2_..._{100,200}.qasm.bak.  The script refuses to overwrite an
existing file, so re-running it is a no-op until you move the current one away.

Output:
  ~/Documents/telesabre/circuits/qasm_100/qnn_nativegates_ibm_qiskit_opt3_100.qasm
  ~/Documents/telesabre/circuits/qasm_200/qnn_nativegates_ibm_qiskit_opt3_200.qasm
"""


import os
import time

import numpy as np
from qiskit import qasm2, transpile
from qiskit.circuit.library import ZZFeatureMap, RealAmplitudes
from qiskit.transpiler import PassManager
from qiskit.transpiler.passes import RemoveBarriers

SIZES = (100, 200)
PARAM_SEED = 0          # fixed so the circuits are reproducible
BASIS = ["rz", "sx", "x", "cx"]

HEADER = (
    "// Deep QNN (ZZ feature map), generated by dsabre/code/gen_deep_qnn.py\n"
    "// Construction: ZZFeatureMap(n, reps=2) o RealAmplitudes(n, reps=1),\n"
    "// parameters bound from numpy default_rng({seed}), then\n"
    "// transpile(basis=[rz,sx,x,cx], optimization_level=3, seed_transpiler=0).\n"
    "// This reproduces MQT Bench v1.1.0's qnn exactly at n=25 (1223 cx) and\n"
    "// n=64 (8126 cx); v2.2.2's qnn is a ZFeatureMap and is NOT equivalent.\n"
    "// Measurements and barriers stripped, per suite convention.\n"
)


def build(n):
    fm = ZZFeatureMap(n, reps=2)
    ansatz = RealAmplitudes(n, reps=1)
    qc = fm.compose(ansatz)
    rng = np.random.default_rng(PARAM_SEED)
    qc = qc.assign_parameters(rng.uniform(0, 2 * np.pi, qc.num_parameters))
    qc = transpile(qc, basis_gates=BASIS, optimization_level=3,
                   seed_transpiler=0)
    qc = qc.remove_final_measurements(inplace=False)
    qc = PassManager([RemoveBarriers()]).run(qc)
    bad = set(qc.count_ops()) - set(BASIS)
    assert not bad, f"n={n}: unexpected ops {bad}"
    return qc


def main():
    for n in SIZES:
        out_dir = os.path.expanduser(f"~/Documents/telesabre/circuits/qasm_{n}")
        path = os.path.join(out_dir, f"qnn_nativegates_ibm_qiskit_opt3_{n}.qasm")
        if os.path.exists(path):
            print(f"n={n}: {os.path.basename(path)} exists, refusing to "
                  f"overwrite", flush=True)
            continue
        t0 = time.time()
        print(f"n={n}: building (expect ~{2*n*(n-1)+n-1:,} CX)...", flush=True)
        qc = build(n)
        cx = qc.count_ops().get("cx", 0)
        pairs = {frozenset(qc.find_bit(q).index for q in inst.qubits)
                 for inst in qc.data if len(inst.qubits) == 2}
        with open(path, "w") as f:
            f.write(HEADER.format(seed=PARAM_SEED) + qasm2.dumps(qc) + "\n")
        print(f"n={n}: {cx:,} CX, depth {qc.depth()}, "
              f"{len(pairs)}/{n*(n-1)//2} pairs entangled, "
              f"{time.time()-t0:.0f}s -> {path}", flush=True)


if __name__ == "__main__":
    main()
