r"""
gen_corenet_table.py — emit the architecture-independence table body.

Two blocks, one per core graph, both on four IBM 27-qubit heavy-hex cores:

  ring  results_heavyhex.json        (4 links, every core degree 2)
  star  results_heavyhex_star.json   (3 links, core 0 a hub, the rest leaves)

Columns follow tab:main — TeleSABRE EPR/SWAP, dSABRE EPR/SWAP, delta EPR — and
the dSABRE column is the production BFS-extended-set router (dSE), the one the
paper calls \dSABRE{}.  Geometric means are taken over the circuits TeleSABRE
completes so the delta is a like-for-like ratio; where that is not the whole
block a second row gives dSABRE's mean over every circuit it routed.

Writes tables/corenet.tex (the table body, to be \input or pasted).
"""

import json, os
from math import prod

_HERE = os.path.dirname(os.path.abspath(__file__))
R   = os.path.join(_HERE, "results")
OUT = os.path.join(_HERE, "tables")
os.makedirs(OUT, exist_ok=True)

BLOCKS = [
    ("results_heavyhex.json",
     r"Ring core graph: 4 inter-core links, every core of degree 2"),
    ("results_heavyhex_star.json",
     r"Star core graph: 3 inter-core links, core 0 a hub of degree 3"),
]

# Suite order, matching every other table in the paper.
ORDER = ["ae", "ghz", "graphstate", "qft", "qnn", "random"]


def gmean(xs):
    xs = [x for x in xs if x is not None and x > 0]
    return prod(xs) ** (1 / len(xs)) if xs else float("nan")


def rows(path):
    recs = {r["circuit"]: r for r in json.load(open(path))["results"]}
    return [recs[c] for c in ORDER if c in recs]


def emit(path, heading):
    out = [r"\multicolumn{7}{@{}l}{\emph{%s}} \\" % heading,
           r"\addlinespace[1pt]"]
    ts_e, ts_l, ds_e, ds_l, all_e, all_l = [], [], [], [], [], []

    for r in rows(path):
        ts = r["ts"]
        d  = r["routers"]["dSE"]
        if d.get("aborted"):
            raise SystemExit(f"dSABRE aborted on {r['circuit']} in {path}")
        star = "$^{\\ast}$" if not ts else ""
        de, dl = d["eprs"], d["ls"]
        all_e.append(de); all_l.append(dl)
        if ts:
            te, tl = ts["eprs"], ts["ls"]
            ts_e.append(te); ts_l.append(tl); ds_e.append(de); ds_l.append(dl)
            delta = f"${100 * (de - te) / te:+.1f}$"
            cells = f"{te} & {tl} & {de} & {dl} & {delta}"
        else:
            cells = f"--- & --- & {de} & {dl} & ---"
        name = r["circuit"].replace("_", r"\_")
        out.append(f"{name}{star} & {r['cx']} & {cells} \\\\")

    out.append(r"\cmidrule(lr){1-7}")
    g = 100 * (gmean(ds_e) - gmean(ts_e)) / gmean(ts_e)
    out.append(r"\textbf{gmean} (%d) &  & %.1f & %.0f & %.1f & %.0f & "
               r"$\mathbf{%+.1f}$ \\"
               % (len(ts_e), gmean(ts_e), gmean(ts_l), gmean(ds_e),
                  gmean(ds_l), g))
    if len(all_e) != len(ds_e):
        out.append(r"\textbf{gmean} (%d) &  & --- & --- & %.1f & %.0f & --- \\"
                   % (len(all_e), gmean(all_e), gmean(all_l)))
    return out, dict(n_ts=len(ts_e), gap=g, ts_e=gmean(ts_e), ds_e=gmean(ds_e),
                     ts_l=gmean(ts_l), ds_l=gmean(ds_l), n_all=len(all_e),
                     all_e=gmean(all_e), all_l=gmean(all_l))


def main():
    body, summary = [], {}
    for i, (fn, heading) in enumerate(BLOCKS):
        path = os.path.join(R, fn)
        if not os.path.exists(path):
            raise SystemExit(f"missing {path}; run bench_heavyhex.py first")
        if i:
            body.append(r"\midrule")
        lines, s = emit(path, heading)
        body += lines
        summary[fn] = s

    dst = os.path.join(OUT, "corenet.tex")
    with open(dst, "w") as f:
        f.write("% GENERATED BY code/gen_corenet_table.py -- do not hand-edit\n")
        f.write("\n".join(body) + "\n")
    print("\n".join(body), flush=True)
    print("\n-- summary --", flush=True)
    for k, v in summary.items():
        print(f"{k}: {v}", flush=True)
    print(f"\nwrote {dst}", flush=True)


if __name__ == "__main__":
    main()
