r"""
gen_regcz_table.py — emit the degree-swept mechanism-ablation table body.

Reads results_regcz_ablation.json (produced by ablate_regular_cz.py --merge)
and writes tables/regcz.tex.

Layout: one absolute row for the full router, then one Delta-gmEPR row per
disabled mechanism -- five numeric columns, one per interaction-graph degree,
which fits an IEEE column where a gmEPR/Delta pair per degree would not.

No TeleSABRE row.  An ablation asks what each of dSABRE's own terms is worth;
an external baseline answers a different question and belongs in the main
comparison, not here.

Writes tables/regcz.tex (the table body, to be pasted).
"""

import json, os
from math import prod

_HERE = os.path.dirname(os.path.abspath(__file__))
R   = os.path.join(_HERE, "results")
OUT = os.path.join(_HERE, "tables")
os.makedirs(OUT, exist_ok=True)

SRC = os.path.join(R, "results_regcz_ablation.json")

# (config key, LaTeX row label) in the order the main-text ablation lists them.
# "no_relief" removed: congestion relief was deleted from the router (see
# CHANGES_FROM_SUBMITTED.md), so there is no longer a mechanism to ablate.
# "no_hopgain" removed on the same basis: hop-gain was deleted from the router.
ROWS = [
    ("no_cap",       r"No capacity penalty ($c_{\mathrm{pen}}=0$)"),
    ("no_lookahead", r"No extended-set lookahead ($w_e=0$)"),
    ("topo_ext",     r"Topological extended set (not BFS)"),
]


def gmean(xs):
    xs = [x for x in xs if x is not None and x > 0]
    return prod(xs) ** (1 / len(xs)) if xs else float("nan")


def main():
    if not os.path.exists(SRC):
        raise SystemExit(f"missing {SRC}; run ablate_regular_cz.py --merge")
    data = json.load(open(SRC))
    recs = data["results"]
    degrees = sorted({r["degree"] for r in recs})

    def gm(config, d):
        sel = [r for r in recs if r["config"] == config and r["degree"] == d]
        ok  = [r["eprs"] for r in sel if not r["aborted"]]
        return gmean(ok), sum(1 for r in sel if r["aborted"]), len(sel)

    full = {d: gm("full", d)[0] for d in degrees}
    out = []

    cells = " & ".join(f"{full[d]:.1f}" for d in degrees)
    out.append(r"\textbf{Full} (gmEPR) & " + cells + r" \\")
    out.append(r"\midrule")
    out.append(r"\multicolumn{%d}{@{}l}{\emph{$\Delta$gmEPR (\%%) with one "
               r"mechanism disabled}} \\" % (len(degrees) + 1))
    out.append(r"\addlinespace[1pt]")

    for key, label in ROWS:
        cells = []
        for d in degrees:
            g, n_ab, n = gm(key, d)
            if n == 0:
                cells.append("---")
            elif n_ab == n:
                cells.append(r"fail")
            else:
                mark = r"$^{\ast}$" if n_ab else ""
                cells.append(f"${100*(g-full[d])/full[d]:+.1f}${mark}")
        out.append(f"{label} & " + " & ".join(cells) + r" \\")

    dst = os.path.join(OUT, "regcz.tex")
    with open(dst, "w") as f:
        f.write("% GENERATED BY code/gen_regcz_table.py -- do not hand-edit\n")
        f.write("\n".join(out) + "\n")
    print("\n".join(out), flush=True)

    print("\n-- absolute gmEPR --", flush=True)
    for key in ["full"] + [k for k, _ in ROWS]:
        print(f"  {key:<14}" + "".join(f"  d={d}: {gm(key,d)[0]:8.1f}"
                                       f"{'(%dab)' % gm(key,d)[1] if gm(key,d)[1] else ''}"
                                       for d in degrees), flush=True)
    print(f"\nwrote {dst}", flush=True)


if __name__ == "__main__":
    main()
