r"""gen_dmax_table.py — emit the entanglement-lifetime table body (tab:dmax).

Reads results/results_dmax_64q.json (bench_dmax_lifetime.py) and
results/results_64q.json, so the dSABRE column is always Table~\ref{tab:main}'s
current one rather than a cached copy, and the D_max=inf column is by
construction Table~\ref{tab:fair}'s physical-model figure.

Writes tables/dmax.tex, and prints the gmean deltas the prose quotes.
"""

import json, os
from math import prod

_HERE = os.path.dirname(os.path.abspath(__file__))
R = os.path.join(_HERE, "results")
OUT = os.path.join(_HERE, "tables")
os.makedirs(OUT, exist_ok=True)

ORDER = ["ae", "ghz", "graphstate", "qft", "qnn", "random",
         "qpeexact", "qaoa", "multiplier"]
COLS = ["inf", "10", "5", "3", "1"]
LABEL = {"ae": "ae", "ghz": "ghz", "graphstate": "graphstate", "qft": "qft",
         "qnn": "qnn", "random": "random", "qpeexact": "qpeexact",
         "qaoa": "qaoa", "multiplier": "multiplier"}


def gmean(xs):
    return prod(xs) ** (1 / len(xs))


def main():
    d = json.load(open(os.path.join(R, "results_dmax_64q.json")))
    if d.get("problems"):
        raise SystemExit("refusing to emit a table from a run with problems:\n  "
                         + "\n  ".join(d["problems"]))
    recs = {r["circuit"]: r for r in d["results"]}
    missing = [c for c in ORDER if c not in recs]
    if missing:
        raise SystemExit(f"missing circuits: {missing}")

    ds = {r["circuit"]: r["routers"]["dSE"]["eprs"]
          for r in json.load(open(os.path.join(R, "results_64q.json")))["results"]}

    body = []
    for c in ORDER:
        r = recs[c]
        assert r["dsabre_eprs"] == ds[c], f"{c}: stale dSABRE column"
        cells = " & ".join(str(r["dmax"][k]) for k in COLS)
        d3 = 100 * (ds[c] - r["dmax"]["3"]) / r["dmax"]["3"]
        body.append(f"{LABEL[c]} & {ds[c]} & {cells} & ${d3:+.1f}$ \\\\")

    body.append(r"\midrule")
    g_ds = gmean([ds[c] for c in ORDER])
    deltas = []
    for k in COLS:
        g = gmean([recs[c]["dmax"][k] for c in ORDER])
        deltas.append(100 * (g_ds - g) / g)
    cells = " & ".join(
        (r"$\mathbf{%+.1f}$" % v) if k == "3" else f"${v:+.1f}$"
        for k, v in zip(COLS, deltas))
    body.append(r"\textbf{gmean} $\Delta$ (\%) & & " + cells + r" & \\")

    dst = os.path.join(OUT, "dmax.tex")
    with open(dst, "w") as f:
        f.write("% GENERATED BY code/gen_dmax_table.py -- do not hand-edit\n")
        f.write("\n".join(body) + "\n")
    print("\n".join(body), flush=True)
    print("\n-- prose figures --", flush=True)
    print(f"dSABRE gmean {g_ds:.1f}", flush=True)
    for k, v in zip(COLS, deltas):
        g = gmean([recs[c]["dmax"][k] for c in ORDER])
        print(f"  D_max={k:<4} pytket gmean {g:8.1f}   dSABRE {v:+6.1f}%", flush=True)
    print(f"\nwrote {dst}", flush=True)


if __name__ == "__main__":
    main()
