r"""gen_fair_percircuit_table.py — per-circuit body for tab:fair_percircuit.

The per-circuit counts behind tab:fair: \texttt{pytket-dqc}'s default
computation on its permissive network, \dSABRE{}'s EPR count, and the
smallest uniform per-server communication capacity under which the
distribution can be materialised.

That last column is `A_required_ebit_mem`.  A positive value is exact; a
negative value -k is the scan's lower bound, printed as ">k" ("was still
failing at k when the budget expired").  A row is daggered -- the
distribution cannot be executed on the device -- when the requirement
provably exceeds the ports available, i.e. need > ports, or the lower bound
k >= ports.  A -k with k < ports settles nothing and is printed n/d.

Writes tables/fair_percircuit.tex.
"""

import json, os, argparse
from math import prod

_HERE = os.path.dirname(os.path.abspath(__file__))
R = os.path.join(_HERE, "results")
OUT = os.path.join(_HERE, "tables")
os.makedirs(OUT, exist_ok=True)

MODEL = "A_published"

SUITES = [
    ("25q", "25 logical qubits, B-grid, 2 ports per core",
     ["ae", "ghz", "graphstate", "qft", "qnn", "random"]),
    ("36q", "36 logical qubits, same B-grid",
     ["bv", "dj", "qaoa", "qpeexact", "vqe\\_su2", "wstate"]),
    ("64q", "64 logical qubits, H-grid, 2--3 ports per core",
     ["ae", "ghz", "graphstate", "qft", "qnn", "random",
      "qpeexact", "qaoa", "multiplier"]),
]


def gmean(xs):
    return prod(xs) ** (1 / len(xs))


def verdict(need, ports):
    """(printable requirement, unbuildable?) -- None means no verdict."""
    if need is None:
        return r"\emph{n/d}", None
    if need > 0:
        return str(need), (need > ports)
    k = -need
    return f"${{>}}{k}$", (True if k >= ports else None)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--fair-pattern", default="results_pytket_fair_v3_{suite}.json")
    args = ap.parse_args()

    body = []
    for i, (suite, heading, order) in enumerate(SUITES):
        rs = {r["circuit"]: r for r in
              json.load(open(os.path.join(R, args.fair_pattern.format(suite=suite))))["results"]
              if r["suite"] == suite}
        ds = {r["circuit"]: r["routers"]["dSE"]["eprs"]
              for r in json.load(open(os.path.join(R, f"results_{suite}.json")))["results"]}
        if i:
            body.append(r"\midrule")
        body.append(r"\multicolumn{4}{@{}l}{\emph{%s}} \\" % heading)
        body.append(r"\addlinespace[1pt]")

        py_all, ds_all = [], []
        for name in order:
            key = name.replace("\\_", "_")
            r = rs[key]
            ports = max(r["degree"].values())
            need, bad = verdict(r.get("A_required_ebit_mem"), ports)
            dag = "$^{\\dagger}$" if bad else ""
            py, d = r[MODEL]["ebits"], ds[key]
            py_all.append(py); ds_all.append(d)
            body.append(f"{name}{dag} & {py} & {d} & {need} \\\\")
        body.append(r"\cmidrule(lr){1-4}")
        body.append(r"\textbf{gmean} & %.1f & %.1f & \\"
                    % (gmean(py_all), gmean(ds_all)))

    dst = os.path.join(OUT, "fair_percircuit.tex")
    with open(dst, "w") as f:
        f.write("% GENERATED BY code/gen_fair_percircuit_table.py -- do not hand-edit\n")
        f.write("\n".join(body) + "\n")
    print("\n".join(body), flush=True)
    print(f"\nwrote {dst}", flush=True)


if __name__ == "__main__":
    main()
