r"""gen_fair_table.py — emit the tab:fair body from the recorded sweep.

\texttt{pytket-dqc} is run with its own default computation (KaHyPar
partitioning via `HypergraphPartitioning`, wrapped by whichever distributor
completes -- `CoverEmbeddingSteinerDetached` where it returns, else
`PartitioningHeterogeneous`), best of five seeds, on a network that gives
every core its full `M` qubits as data and leaves communication capacity
unbounded.  That network is MORE PERMISSIVE than the device \dSABRE{} routes
on, which reserves deg(c) of the M qubits as communication ports and can hold
only deg(c) link qubits at a time, so the e-bit counts below are a lower
bound on what the device would actually cost.

Columns: pytket-dqc's e-bits, \dSABRE{}'s EPR count from the suite's own
results file, the delta, and how many of the suite's distributions cannot be
materialised within the device's communication capacity.

That last column is read from `A_required_ebit_mem`, the smallest uniform
per-server communication capacity under which the distribution can be built.
A positive value is an exact answer; a negative value -k is the scan's lower
bound ("needs more than k"), which still settles the question whenever
k >= ports.  Only a -k with k < ports is genuinely inconclusive, and those
are excluded from the count, so the column is a LOWER bound on how many
distributions are unbuildable.

Writes tables/fair.tex.
"""

import json, os, argparse
from math import prod

_HERE = os.path.dirname(os.path.abspath(__file__))
R = os.path.join(_HERE, "results")
OUT = os.path.join(_HERE, "tables")
os.makedirs(OUT, exist_ok=True)

SUITES = [("25q", "25 logical qubits"),
          ("36q", "36 logical qubits"),
          ("64q", "64 logical qubits")]

MODEL = "A_published"      # pytket-dqc's default computation, permissive network


def gmean(xs):
    return prod(xs) ** (1 / len(xs))


def buildable(need, ports):
    """True/False/None: can this distribution be built within `ports`?"""
    if need is None:
        return None
    if need > 0:
        return need <= ports
    k = -need                      # scan bound: "needs more than k"
    return False if k >= ports else None


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--fair-pattern", default="results_pytket_fair_v3_{suite}.json")
    args = ap.parse_args()

    body, notes = [], []
    tot_unbuildable = tot_circuits = 0
    for suite, label in SUITES:
        fair_path = os.path.join(R, args.fair_pattern.format(suite=suite))
        if not os.path.exists(fair_path):
            raise SystemExit(f"missing {fair_path}")
        rs = [r for r in json.load(open(fair_path))["results"]
              if r["suite"] == suite]
        ds_recs = json.load(open(os.path.join(R, f"results_{suite}.json")))["results"]
        ds = {r["circuit"]: r["routers"]["dSE"]["eprs"] for r in ds_recs}

        missing = [r["circuit"] for r in rs if r["circuit"] not in ds]
        if missing:
            raise SystemExit(f"{suite}: no dSABRE result for {missing}")
        truncated = [r["circuit"] for r in rs if r[MODEL].get("seed_loop_truncated")]
        if truncated:
            notes.append(f"{suite}: {MODEL} seed loop did not complete all five "
                         f"seeds on {truncated}")

        py = gmean([r[MODEL]["ebits"] for r in rs])
        dsg = gmean([ds[r["circuit"]] for r in rs])
        delta = 100 * (dsg - py) / py

        verdicts = [buildable(r.get("A_required_ebit_mem"),
                              max(r["degree"].values())) for r in rs]
        unbuildable = sum(1 for v in verdicts if v is False)
        inconclusive = sum(1 for v in verdicts if v is None)
        if inconclusive:
            notes.append(f"{suite}: {inconclusive} circuit(s) inconclusive; "
                         f"the unbuildable count is a lower bound")
        tot_unbuildable += unbuildable
        tot_circuits += len(rs)

        sign = "" if delta < 0 else r"\phantom{+}"
        body.append(f"{label}  & {py:5.1f} & {dsg:5.1f} & "
                    f"${sign}{delta:+.1f}$ & {unbuildable}/{len(rs)} \\\\")
        print(f"{suite}: n={len(rs)} pytket={py:.1f} dSABRE={dsg:.1f} "
              f"delta={delta:+.1f}% unbuildable={unbuildable}/{len(rs)}"
              f"{f' (+{inconclusive} inconclusive)' if inconclusive else ''}",
              flush=True)

    dst = os.path.join(OUT, "fair.tex")
    with open(dst, "w") as f:
        f.write("% GENERATED BY code/gen_fair_table.py -- do not hand-edit\n")
        f.write("\n".join(body) + "\n")
    print("\n" + "\n".join(body), flush=True)
    print(f"\ntotal unbuildable: {tot_unbuildable}/{tot_circuits}", flush=True)
    if notes:
        print("\n-- notes --", flush=True)
        for n in notes:
            print("  " + n, flush=True)
    print(f"\nwrote {dst}", flush=True)


if __name__ == "__main__":
    main()
